language: dart

dart:
- dev

jobs:
  include:
    - stage: analyze_and_format
      name: "Analyze lib/"
      os: linux
      script: dartanalyzer --fatal-warnings --fatal-infos lib/
    - stage: analyze_and_format
      name: "Analyze test/"
      os: linux
      script: dartanalyzer --enable-experiment=non-nullable --fatal-warnings --fatal-infos test/
    - stage: analyze_and_format
      name: "Format"
      os: linux
      script: dartfmt -n --set-exit-if-changed .
    - stage: test
      name: "Vm Tests"
      os: linux
      script: pub run --enable-experiment=non-nullable test -p vm
    - stage: test
      name: "Web Tests"
      os: linux
      script: pub run --enable-experiment=non-nullable test -p chrome

stages:
  - analyze_and_format
  - test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master, null_safety]

# Incremental pub cache and builds.
cache:
  directories:
  - $HOME/.pub-cache
