language: dart

dart:
- 2.3.0
- dev

dart_task:
- test

matrix:
  include:
  # Only validate formatting using the dev release
  - dart: dev
    dart_task: dartfmt
  - dart: dev
    dart_task:
      dartanalyzer: --fatal-infos --fatal-warnings .
  - dart: 2.3.0
    dart_task:
      dartanalyzer: --fatal-warnings .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

# Incremental pub cache and builds.
cache:
  directories:
  - $HOME/.pub-cache
