name: collection
version: 1.19.0
description: >-
  Collections and utilities functions and classes related to collections.
repository: https://github.com/dart-lang/collection

topics:
 - data-structures
 - collections

environment:
  sdk: ^3.4.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
