name: collection
version: 1.9.1
author: Dart Team <misc@dartlang.org>
description: Collections and utilities functions and classes related to collections.
homepage: https://www.github.com/dart-lang/collection
environment:
  sdk: '>=1.12.0 <2.0.0'
dev_dependencies:
  test: '^0.12.0'
