name: collection
version: 1.14.7-dev
author: Dart Team <misc@dartlang.org>
description: Collections and utilities functions and classes related to collections.
homepage: https://www.github.com/dart-lang/collection

environment:
  # Required for Dart 2.0 collection changes.
  sdk: '>=2.0.0-dev.22.0 <2.0.0'

dev_dependencies:
  build_runner: ^0.7.11
  build_test: ^0.10.0
  build_web_compilers: ^0.3.1
  test: ^0.12.0
